package:
    name: tidymongo
    version: {{ environ.GIT_DESCRIBE_TAG.replace('-', '_') }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
    git_url: .

requirements:
    build:
        - setuptools
        - python
test:
    imports:
        - tidymongo
